### ISSUE TITLE
yarn devphase init: no such file or directory: .gitignore

### ISSUE THREAD

**Issue by kvinwang** [l00k/devphase#14]
I was just following the instructions in README and got an error:
```bash
$ yarn devphase init
yarn run v1.22.19
warning package.json: No license field
$ /home/kvin/codes/chain/phala/play-contract/play-devphase/node_modules/.bin/devphase init
Couldn't find tsconfig.json. tsconfig-paths will be skipped
[Init] Initiation
[Initializer] Creating files
[Initializer] .gitignore
Error: ENOENT: no such file or directory, copyfile '/home/kvin/codes/chain/phala/play-contract/play-devphase/node_modules/devphase/templates/.gitignore' -> './.gitignore'
    at Object.copyFileSync (node:fs:2852:3)
    at Initializer.init (/home/kvin/codes/chain/phala/play-contract/play-devphase/node_modules/devphase/dist/cli/index.js:939:29)
    at async command (/home/kvin/codes/chain/phala/play-contract/play-devphase/node_modules/devphase/dist/cli/index.js:962:3) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/home/kvin/codes/chain/phala/play-contract/play-devphase/node_modules/devphase/templates/.gitignore',
  dest: './.gitignore'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by l00k** [comment]
Thx fixed in `^0.0.19`
